version: '3.6'
services:
  backend:
    build: ./backend
    ports:
      - '127.0.0.1:8989:80'

  web-server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - cache_path:/md/cache
    ports:
      - '127.0.0.1:9999:80'
    depends_on:
      - backend
    links:
      - backend

volumes:
  cache_path:
