version: "3"

services:
  master:
    container_name: citus_master
    image: citusdata/citus:12.1.1
    ports: 
    - 5432:5432
    labels: ["com.citusdata.role=Master"]
    env_file:
      - ./../config.env
  worker:
    image: citusdata/citus:12.1.1
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    env_file:
      - ./../config.env
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    container_name: citus_manager
    image: citusdata/membership-manager:0.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    env_file:
      - ./../config.env

volumes:
  healthcheck-volume: