version: '3.7'
services:
  lb:
    image: nginx
    restart: always
    volumes:
      - ./configs/lb.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '127.0.0.1:9999:80'
  uk:
    image: nginx
    volumes:
      - ./configs/node.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/uk.html:/www/data/index.html:ro
    # ports:
    #   - '127.0.0.1:9999:80'
  us1:
    image: nginx
    volumes:
      - ./configs/node.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/us1.html:/www/data/index.html:ro
    # ports:
    #   - '127.0.0.1:9998:80'
  us2:
    image: nginx
    volumes:
      - ./configs/node.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/us2.html:/www/data/index.html:ro
    # ports:
    #   - '127.0.0.1:9997:80'
  rest:
    image: nginx
    volumes:
      - ./configs/node.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/rest.html:/www/data/index.html:ro
    # ports:
    #   - '127.0.0.1:9996:80'
  backup:
    image: nginx
    volumes:
      - ./configs/node.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/backup.html:/www/data/index.html:ro
    # ports:
    #   - '127.0.0.1:9995:80'
