version: '3.3'

volumes:
  fbdata: {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"

  filebeat:
    container_name: filebeat
    hostname: filebeat
    user: root
    image: docker.elastic.co/beats/filebeat:7.4.0
    volumes:
      #Mount the filebeat configuration so users can make edit
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      #Mount the mysql logs into the filebeat container so we can access and and index them using the filebeat mysql module
      - ./db/logs:/var/log/mysql/
      #Named volume fbdata. This is used to persist the registry file between restarts, so to avoid data duplication
      - fbdata:/usr/share/filebeat/data/
    command: filebeat -strict.perms=false
    restart: on-failure

  db:
    image: mysql:5.7
    container_name: mysql
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
    volumes:
      - "./db/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
      - "./db/data:/var/lib/mysql:rw"
      - "./db/logs:/var/log/mysql/"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  mongo:
    image: mongo:5.0.13

  graylog:
    image: graylog/graylog:5.1
    environment:
  # CHANGE ME (must be at least 16 characters)!
    - GRAYLOG_PASSWORD_SECRET=2c74fd17edafd80e8447b0d46741ee243b7eb74dd2149a0ab1b9246fb30382f27e853d8585719e0e67cbda0daa8f51671064615d645ae27acb15bfb1447f459b
  # Password: admin
    - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
  # Graylog web interface and REST API
    - 9000:9000
  # Syslog TCP
    - 1514:1514
  # Syslog UDP
    - 1514:1514/udp
  # GELF TCP
    - 12201:12201
  # GELF UDP
    - 12201:12201/udp