version: '3.7'

services:
  app:
    build: ./app
    env_file: config.env
    ports:
      - '127.0.0.1:8989:80'
    depends_on:
      - redis-rdb
      - redis-aof
      - beanstalkd
    links:
      - redis-rdb
      - redis-aof
      - beanstalkd

  redis-rdb:
    image: redis:7.0.9
    volumes:
      - "./redis-rdb.conf:/usr/local/etc/redis/redis.conf"
      - "data-rdb:/data"
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
 
  redis-aof:
    image: redis:7.0.9
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "data-aof:/data"
      - "./redis-aof.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "6380:6379"

  beanstalkd:
    image: trovit/beanstalkd:latest
    container_name: beanstalkd
    volumes:
      - data-beanstalkd:/var/lib/beanstalkd

  beanstalkd-ui:
    image: thedavis/beanstalkd-ui
    ports:
      - 8008:80
    environment:
      - BEANSTALKD_HOST=beanstalkd
      - BEANSTALKD_PORT=11300
    links:
      - beanstalkd
    
volumes:
  data-rdb:
  data-aof:
  data-beanstalkd:
     