name: Test and deploy on staging

on: [push]
  # push:
  #   branches:
  #     - main

defaults:
  run:
    working-directory: ./26_cd/queue/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/build_test_deploy
        with:
          target-environment: 'STG'
