name: Test and deploy on staging

on: [push]
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./26_cd/queue/

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/build_test_deploy/
        with:
          target-environment: 'STG'
