name: Test and deploy on staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build, test and deploy to staging
        uses: ./.github/actions/build_test_deploy/
        with:
          target-environment: 'STG'
          working-directory: ./26_cd/queue/
