name: Test and Deploy on staging

on: [push]
  # push:
  #   branches:
  #     - main

env:
  APP_PATH: "26_cd/queue/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Move to app directory
        run: |
          echo "APP_PATH: $APP_PATH"
          cd $APP_PATH
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
